name: "Build"
on:
  push:

defaults:
  run:
    shell: bash

jobs:

  windows:
    runs-on: windows-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2
    - name: "Install SDL2"
      run: |
        version="2.0.12"
        archive="SDL2-devel-$version-mingw.tar.gz"
        curl -LO https://www.libsdl.org/release/$archive
        tar -xaf $archive
        cd SDL2-$version
        make native
    - name: "Install SDL2_image"
      run: |
        version="2.0.5"
        archive="SDL2_image-devel-$version-mingw.tar.gz"
        curl -LO https://www.libsdl.org/projects/SDL_image/release/$archive
        tar -xaf $archive
        cd SDL2_image-$version
        make native
    - name: "Compile"
      run: |
        make SDL_CONFIG=/usr/bin/sdl2-config bin/brogue.exe
    - name: "Package DLLs"
      run: |
        cp /usr/bin/{SDL2,SDL2_image,zlib1,libpng16-16}.dll bin
    - name: "Upload artifact"
      uses: actions/upload-artifact@v1
      with:
        name: windows-mingw-bin
        path: bin
